[package]
name = "reqwest-conditional-middleware"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.51"
reqwest = { version = "0.11", default-features = false }
reqwest-middleware = { version = "0.1.5" }
task-local-extensions = "0.1.1"

[dev-dependencies]
http = "0.2"
tokio = { version = "1.6", features = ["full"] }
